/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dataStructure;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

@Getter
@Setter
@AllArgsConstructor
@ToString
public class Library {

    String name;
    String autor;

    public boolean someLibraryMethod() {
        return true;
    }
}
