/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dataStructure;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

@Getter
@Setter
@AllArgsConstructor
@ToString
public class Library implements Comparable<Library>{

    int id;
    String name;
    String autor;

    public boolean someLibraryMethod() {
        return true;
    }

    @Override
    public int compareTo(Library lib) {
        if(this.id==lib.getId()){
            return 0;
        }else if(this.id<lib.getId()){
            return -1;
        }else{return 1;}
    }
}
