/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dataStructure;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library("Harry Potter 4", "J. K. Rowling");
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
